# RUBJOB Cloudflare Configuration
name = "rubjob"
compatibility_date = "2026-04-07"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_LIFF_ID = "2009652089-lRGKgXfJ"

[[d1_databases]]
binding = "DB" # The binding name available in your worker/app
database_name = "rubjob-db"
database_id = "617d4342-c1c3-4216-8e83-03cc1a6bd57d"
migrations_dir = "db"
