# RUBJOB Cloudflare Configuration
name = "rubjob"
compatibility_date = "2024-03-28"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_LIFF_ID = "2009652089-lRGKgXfJ"

[[d1_databases]]
binding = "DB" # The binding name available in your worker/app
database_name = "rubjob-db"
database_id = "8e8b099a-249f-40fc-9d1b-72f765586cf6"
migrations_dir = "db"
